version: '3.8'

services:
  hub:
    image: selenium/hub:4.27
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
  chrome:
    image: selenium/node-chromium:4.27
    shm_size: '2gb'
   
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
    depends_on:
      - hub
  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2gb'
    
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=3
      - SE_NO_VNC_PASSWORD=secret
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - hub
  edge:
    image: selenium/node-edge:4.27
    shm_size: '2gb'
    
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_NO_VNC_PASSWORD=secret
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - hub
  Flight-portal:
    image: gkdocker/selenium
    depends_on:
      - chrome
      - firefox
      - edge
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - .output/flight-portal:/home/selenium-docker/test-output
          
  
  
  
    