services:
  hub:
    image: selenium/hub:4.27
  chrome:
    image: selenium/node-chromium:4.27
    shm_size: '2gb'
   
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file:
      - .env
  # Uncomment the following lines to enable Chrome with GPU support
  firefox:
    image: selenium/node-firefox:4.27
    shm_size: '2gb'
    
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file:
      - .env
  edge:
    image: selenium/node-edge:4.27
    shm_size: '2gb'
    
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file:
      - .env